apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-nonprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/S4k1dl0/nonprod-k8s-manifests.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true