apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: nonprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart
        image: your-registry/cart:latest
        ports:
        - containerPort: 8080